---
openapi: 3.0.1
info:
  title: Company Manager API V1
  version: v1
components:
  schemas:
    bad_request:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
        details:
          type: array
          items:
            type: object
      required:
      - errors
    address:
      type: object
      properties:
        id:
          type: integer
        street:
          type: string
        city:
          type: string
        postal_code:
          type: string
          nullable: true
        country:
          type: string
      required:
      - id
      - street
      - city
      - country
    addresses:
      type: array
      items:
        "$ref": "#/components/schemas/address"
    company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        registration_number:
          type: integer
        addresses:
          "$ref": "#/components/schemas/addresses"
      required:
      - id
      - name
      - registration_number
paths:
  "/api/v1/companies":
    post:
      summary: Create a Company with Addresses
      tags:
      - Companies
      parameters: []
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/company"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/bad_request"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                registration_number:
                  type: integer
                addresses_attributes:
                  "$ref": "#/components/schemas/addresses"
              required:
              - name
              - registration_number
              - addresses_attributes
  "/api/v1/companies/import":
    post:
      summary: Bulk Import Companies via CSV
      tags:
      - Companies
      parameters: []
      responses:
        '201':
          description: Companies imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/company"
                  metadata:
                    type: object
                    properties:
                      total_count:
                        type: number
                required:
                - data
                - metadata
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/bad_request"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
  "/api/v1/companies/import_async":
    post:
      summary: Bulk async Import Companies via CSV
      tags:
      - Companies
      parameters: []
      responses:
        '201':
          description: Companies import created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  import_id:
                    type: string
                required:
                - import_id
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/bad_request"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
